package com.jhonatansouza.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import java.util.Objects;

@DynamoDBTable(tableName = "Planets")
public class PlanetModel {

    private String hashId;
    @DynamoDBAttribute(attributeName = "name")
    private String name;
    @DynamoDBAttribute(attributeName = "climate")
    private String climate;
    @DynamoDBAttribute(attributeName = "terrain")
    private String terrain;
    @DynamoDBAttribute(attributeName = "moviesAmount")
    @Min(0)
    @Max(Integer.MAX_VALUE)
    private Integer moviesAmount;


    @DynamoDBHashKey(attributeName = "hashId")
    @DynamoDBAutoGeneratedKey
    public String getHashId() {
        return hashId;
    }

    public void setHashId(String hashId) {
        this.hashId = hashId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getClimate() {
        return climate;
    }

    public void setClimate(String climate) {
        this.climate = climate;
    }

    public String getTerrain() {
        return terrain;
    }

    public void setTerrain(String terrain) {
        this.terrain = terrain;
    }

    public Integer getMoviesAmount() {
        return moviesAmount;
    }

    public void setMoviesAmount(Integer moviesAmount) {
        this.moviesAmount = moviesAmount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PlanetModel)) return false;
        PlanetModel that = (PlanetModel) o;
        return Objects.equals(getHashId(), that.getHashId()) &&
                Objects.equals(getName(), that.getName()) &&
                Objects.equals(getClimate(), that.getClimate()) &&
                Objects.equals(getTerrain(), that.getTerrain()) &&
                Objects.equals(getMoviesAmount(), that.getMoviesAmount());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getHashId());
    }


}